#!/bin/sh
cd "${0%/*}" || exit                            # Run from this directory
targetType=libso
. "${WM_PROJECT_DIR:?}"/wmake/scripts/AllwmakeParseArguments

#------------------------------------------------------------------------------
# Build into FOAM_USER_{APPBIN,LIBBIN} unless otherwise specified with
# -prefix or FOAM_MODULE_{APPBIN,LIBBIN} env varables

moduleName="NN_Pred"

if [ "$FOAM_MODULE_PREFIX" = false ]
then
    echo "Compilation of $moduleName is disabled (prefix=false)"
    exit 0
fi

echo "========================================"
date "+%Y-%m-%d %H:%M:%S %z" 2>/dev/null || echo "date is unknown"
echo "Starting compile of $moduleName with ${WM_PROJECT_DIR##*/}"
echo "  $WM_COMPILER $WM_COMPILER_TYPE compiler"
echo "  ${WM_OPTIONS}, with ${WM_MPLIB} ${FOAM_MPI}"
echo "  prefix = ${FOAM_MODULE_PREFIX:-default (user)}"
echo


echo "========================================"
echo "Activating environment..."
source ./activate.sh  # Source the activate script to set up the environment

echo "========================================"
echo "Building Predictor-Core..."
Predictor-Core/Allwmake || { echo "Allwmake in Predictor-Core failed"; exit 1; }

echo "========================================"
echo "Compiling OpenFOAM-Extension"
OpenFOAM-Extension/Allwmake || { echo "Allwmake in OpenFOAM-Extension failed"; exit 1; }


# Some summary information
echo
date "+%Y-%m-%d %H:%M:%S %z" 2>/dev/null || echo "date is unknown"
echo "========================================"
echo "  Finished compile of $moduleName with ${WM_PROJECT_DIR##*/}"
echo "  $WM_COMPILER $WM_COMPILER_TYPE compiler"
echo "  ${WM_OPTIONS}, with ${WM_MPLIB} ${FOAM_MPI}"
echo

