#!/bin/sh

# Ensure the script runs from its current directory
cd "${0%/*}" || exit

echo "========================================"
echo "Checking and downloading third-party libraries..."
cd third_party || exit
# Check if the third-party libraries exist, if not, download them.
./DownloadThirdParty.sh || { echo "Downloading third-party libraries failed"; exit 1; }
cd ..  # Go back to the Predictor-Core directory

echo "========================================"
echo "Compiling Predictor-Core..."
make clean && make || { echo "Compilation of Predictor-Core failed"; exit 1; }
