#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

cd Stick_Ideal
./Allclean
cd ..

cd Stick_ML_TF
./Allclean
cd ..

cd Stick_ML_ONNX
./Allclean
cd ..

#------------------------------------------------------------------------------
