#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory


cd Stick_Ideal
./Allrun
cd ..

export NNPRED_BACKEND="TF"
cd Stick_ML_TF
./Allrun
cd ..

export NNPRED_BACKEND="ONNX"
cd Stick_ML_ONNX
./Allrun
cd ..


# -----------------------------------------------------------------------------
